name: Update Github Stats

on:
  schedule:
    - cron: "10 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install requirements
        run: |
          npm install

      - name: Github Configurations
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "action@github.com"
          git pull

      - name: Print Debug Info
        run: |
          echo "Repository Owner: ${{ github.repository_owner }}"
          echo "Repository: ${{ github.repository }}"

      - name: Update Template
        run: |
          node updater.js ${{ github.repository_owner }} atom
        env:
          GHT: ${{ secrets.GHT }}

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git add .
          git commit -m "Github Stats updated 🎉" || echo "No changes to commit"
          git push https://oauth2:${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/Terminal-Style.git HEAD:main
